# Generated by Django 3.1.4 on 2020-12-20 18:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('content', '0001_initial'), ('content', '0002_auto_20201220_1131')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
    ]
